fand/fand/theaters/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'theaters'

urlpatterns = [
    path('', views.home, name='home'),
    path('movies/', views.list_movies, name='movies-list'),
    path('movies/<int:pk>', views.movie, name='movies-detail'),
    path('theaters/', views.list_theaters, name='theaters-list'),
    path('theaters/<slug:pk>', views.theater, name='theaters-detail'),
    path('showtimes/', views.list_showtimes, name='showtimes-list'),
    path('api/<slug:slug>/', views.api, name='api'),
]

fand/fand/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('fand.theaters.urls')),
    path('admin/', admin.site.urls),
]

fand/fand/theaters/models.py
from django.db import models

from django.urls import reverse
#
# GENDER_CHOICES = (
#     ('male', 'Male'),
#     ('female', 'Female'),
# )

# class Category(models.Model):
#     name = models.CharField(max_length=100)
#
#     class Meta:
#         ordering = ('name',)
#
#     def __str__(self):
#         return self.name

class Theater(models.Model):
    addressOne = models.CharField(max_length=200)
    addressTwo = models.CharField(max_length=200, null=True)
    agePolicy = models.CharField(max_length=400, null=True)
    city = models.CharField(max_length=100)
    theaterName = models.CharField(max_length=200)
    phone = models.CharField(max_length=20, null=True)
    state = models.CharField(max_length=20)
    zip = models.CharField(max_length=5)
    id = models.CharField(max_length=100, primary_key=True)
    # alpha_code = models.CharField(max_length=3, blank=True, null=True)
    # numeric_code = models.CharField(max_length=3, blank=True, null=True)
    lat = models.CharField(max_length=10, blank=True, null=True)
    lng = models.CharField(max_length=10, blank=True, null=True)

    # showtimes = models.ForeignKey(Showtimes, "CASCADE")
    # movies = models.ForeignKey(Movie, "CASCADE")

    # def __str__(self):
    #     return "{} {} - {} ({})".format(self.location.name, self.movies.title, self.showtimes)
#
    def __str__(self):
        return "{} - {}".format(self.theaterName, self.city)

class Movie(models.Model):
    title = models.CharField(max_length=100)
    movid = models.CharField(max_length=100, primary_key=True, default=0)
    # gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    # dob = models.DateField()

    runtime = models.CharField(max_length=6)
    genres = models.CharField(max_length=120)
    # releaseDate = models.DateField(null=True)
    rating = models.CharField(max_length=6)
    poster = models.CharField(max_length=1000)

    theaters = models.ManyToManyField(Theater)
    # theaters = models.ForeignKey(Theater, "CASCADE")
    #this movie is playing at these theaters
    #one to many relationship
    class Meta:
        ordering = ('title',)

    def __str__(self):
        #return self.name
        return "{}".format(self.title,)

class Showtime(models.Model):
    time = models.CharField(max_length=8)
    # ticketingDate = models.CharField(max_length=10)
    showid = models.CharField(max_length=100)
    # type = models.CharField(max_length=200)
    ticketingUrl = models.CharField(max_length=400)
    # movie = models.ManyToManyField(Movie)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, null=True)
    theater = models.ForeignKey(Theater, on_delete=models.CASCADE, null=True)
    # theater = models.ForeignKey(Theater, on_delete=models.CASCADE, default="0")

    # movies = models.ForeignKey(Movie, "CASCADE")
    #"this movie plays at this many times"
    #one to many relationship
    class Meta:
        ordering = ('time',)

    def __str__(self):
        return "{} - Movie: {} - Theater: {}".format(self.time,self.movie,self.theater)

    # def to_json(self):
    #     return {
            # "name": self.name,
            # "alpha_code": self.alpha_code,
            # "numeric_code": self.numeric_code,
            # "lat": self.lat,
            # "lng": self.lng,
        # }



# class Theater(models.Model):
#     location = models.ForeignKey(Location, "CASCADE")
#     showtimes = models.ForeignKey(Showtimes, "CASCADE")
#     movies = models.ForeignKey(Movie, "CASCADE")
#
#     def __str__(self):
#         return "{} {} - {} ({})".format(self.location.name, self.movies.title, self.showtimes)
# #
#     def get_absolute_url(self):
#         from django.urls import reverse
#         return reverse('winners:winners-detail', args=[str(self.id)])
#
#     def to_json(self):
#         return {
#             "name": self.person.name,
#             "gender": self.person.gender,
#             "category": self.category.name,
#             "country": self.country.to_json(),
#             "year": self.year,
#         }
#
#     # def get_absolute_url(self):
#     #     return reverse('winners-detail',args={'person': self.person})



# class Winner(models.Model):
#     person = models.ForeignKey(Person, "CASCADE")
#     category = models.ForeignKey(Category, "CASCADE")
#     country = models.ForeignKey(Country, "CASCADE")
#     year = models.PositiveIntegerField()
#
#     def __str__(self):
#         return "{} {} - {} ({})".format(self.person.name, self.category, self.country, self.year)
#
#     def get_absolute_url(self):
#         from django.urls import reverse
#         return reverse('winners:winners-detail', args=[str(self.id)])
#
#     def to_json(self):
#         return {
#             "name": self.person.name,
#             "gender": self.person.gender,
#             "category": self.category.name,
#             "country": self.country.to_json(),
#             "year": self.year,
#         }
#
#     # def get_absolute_url(self):
#     #     return reverse('winners-detail',args={'person': self.person})

fand/fand/theaters/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from django.forms.models import model_to_dict

# Create your views here.
# ^CSabrinas-MacBook-Pro-3:fand sabrina$ docker run -v $PWD:/opt/project -it -p 8000:8000 nobel-app ./env/bin/python3and/manage.py shell
# Python 3.5.2 (default, Nov 23 2017, 16:37:01)
# [GCC 5.4.0 20160609] on linux
# Type "help", "copyright", "credits" or "license" for more information.
# (InteractiveConsole)
# ******** >>> from fand.theaters.models import*
# >>> Showtime.objects.values_list("time")
# <QuerySet [('10:00p',), ('10:00p',), ('10:00p',), ('10:00p',), ('10:00p',), ('10:05p',), ('10:10p',), ('10:10p',), ('10:10p',), ('10:10p',), ('10:15p',), ('10:15p',), ('10:15p',), ('10:15p',), ('10:20p',), ('10:20p',), ('10:20p',), ('10:30p',), ('10:30p',), ('10:30p',), '...(remaining elements truncated)...']>
# >>> Showtime.objects.values_list("time").distinct()
# <QuerySet [('10:00p',), ('10:05p',), ('10:10p',), ('10:15p',), ('10:20p',), ('10:30p',), ('10:35p',), ('10:40p',), ('10:50p',), ('11:00a',), ('11:00p',), ('11:10a',), ('11:20a',), ('11:30p',), ('12:00p',), ('12:05p',), ('12:10p',), ('12:15p',), ('12:20p',), ('12:25p',), '...(remaining elements truncated)...']>
# ******** >>> times=Showtime.objects.values_list("time", flat=True).distinct()
# <QuerySet ['10:00p', '10:05p', '10:10p', '10:15p', '10:20p', '10:30p', '10:35p', '10:40p', '10:50p', '11:00a', '11:00p', '11:10a', '11:20a', '11:30p', '12:00p', '12:05p', '12:10p', '12:15p', '12:20p', '12:25p', '...(remaining elements truncated)...']>
# >>>


# >>> Showtime.objects.filter(time="11:30p")
# <QuerySet [<Showtime: 11:30p>]>
# >>> Showtime.objects.filter(time="10:00p")
# <QuerySet [<Showtime: 10:00p>, <Showtime: 10:00p>, <Showtime: 10:00p>, <Showtime: 10:00p>, <Showtime: 10:00p>]>
# >>> Movie.objects.filter(showtime__in=Showtime.objects.filter(time="10:00p"))
# <QuerySet [<Movie: Blockers - ID: 206654>, <Movie: Blumhouse's Truth or Dare (2018) - ID: 208538>, <Movie: Chappaquiddick - ID: 206369>, <Movie: Love, Simon - ID: 208042>, <Movie: Ready Player One - ID: 204139>]>
# >>> give me all the movies where the showtime query is 10 pm

from .models import *

def home(request):
    return render(request, "fand/home.html", {})

def movie(request, pk):
    movie = Movie.objects.get(movid=pk)
    showtimes = Showtime.objects.filter(movie=pk)
    consolidated = {}
    for st in showtimes:
        if st.theater not in consolidated:
            consolidated[st.theater] = []
        consolidated[st.theater] += [st]
    return render(request, "fand/movie.html", {'m': movie,
                                                'consolidated': consolidated,
                                                })

def theater(request, pk):
    theater = Theater.objects.get(id=pk)
    showtimes = Showtime.objects.filter(theater=pk)
    consolidated = {}
    for st in showtimes:
        if st.movie not in consolidated:
            consolidated[st.movie] = []
        consolidated[st.movie] += [st]

    return render(request, "fand/theater.html", {'t': theater ,
                                                'consolidated': consolidated,
                                                })

def list_movies(request):
    movies = Movie.objects.all()
    return render(request, "fand/list_movies.html", {'movies': movies})

def list_theaters(request):
    theaters = Theater.objects.all()
    return render(request, "fand/list_theaters.html", {'theaters' : theaters })

def list_showtimes(request):
    return render(request, "fand/list_showtimes.html", {})

def api(request, slug):

    if slug == 'movies':
        data = Movie.objects.values()
    elif slug == 'showtimes':
        data = Showtime.objects.values()
    else:
        data = Theater.objects.values()

    f_data = {"Data": [w for w in data]}

    return JsonResponse(f_data)
    # return render(request, "fand/api.html", {})

fand/fand/theaters/templates/fand/api.html
{% extends "fand/base.html" %}

{% block content %}
API coming soon (delete this page eventually)
{% endblock %}

fand/fand/theaters/templates/fand/base.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GoTicket</title>
    <link href="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static "fand/css/boot.css" %}" rel="stylesheet">

    <!-- {% block css %}
        {{ block.super }}
        <link rel ="stylesheet" href="{% static "winners/css/map.css" %}">
    {% endblock %} -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block body %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <!-- Navbar content -->
      <a class="navbar-brand navbar-brand-pac" href="{% url "theaters:home" %}">GoTicket</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{% url "theaters:home" %}">Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{% url "theaters:theaters-list" %}">Theaters</a>
          <a class="nav-item nav-link" href="{% url "theaters:movies-list" %}">Movies</a>

      </div>
        <span class="navbar-text ml-auto">
          Featuring NC Triangle Locations
        </span>
      </div>
    </nav>
    {% block header %}
    {% endblock %}
      <div class="container">


          {% block breadcrumb_nav %}
              <!-- <nav aria-label="breadcrumb">
                  <ol class="breadcrumb">
                      {% block breadcrumbs %}
                      {% endblock %}

                  </ol>
              </nav> -->
          {% endblock %}
          {% block content %}
          {% endblock %}
      </div>
    {% endblock %}


    <script
    src="https://code.jquery.com/jquery-3.3.1.js"
    integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script src="https://unpkg.com/topojson@3"></script>
    <script src="{% static "fand/js/home.js" %}"></script>
    <script src="{% static "fand/js/bar.js" %}"></script>

    <script src="{% static "fand/js/movie-map.js" %}"></script>


    {% block script %}{% endblock %}
  </body>
</html>

fand/fand/theaters/templates/fand/home.html
{% extends "fand/base.html" %}
{% load static %}
<link href="{% static "fand/css/boot.css" %}" rel="stylesheet">

{% block header %}
<!-- header design credit: https://github.com/BlackrockDigital/startbootstrap-one-page-wonder -->
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading">Get a movie on!</h1>
      <h2 class="masthead-subheading">We'll help you find one.</h2>
      <a href="{% url "theaters:movies-list" %}" class="btn btn-primary btn-xl rounded-pill mt-5">See a movie</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block content %}
<!-- home text here -->
{% endblock %}

fand/fand/theaters/templates/fand/list_movies.html
{% extends "fand/base.html" %}
{% load static %}
<link href="{% static "fand/css/boot.css" %}" rel="stylesheet">

{% block content %}
<br>

<div class="row">
  <div class="col-md-12">
    <h1>Movies</h1>
    <p>Here's all of the movies. Interested in one? Click to view more information and showtimes. </p>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <h2>Featured Movie</h2>
    <h4>Sgt. Stubby: An American Hero</h4>
    <div class="row">
      <div class="col-md-3">
        <img src="http://images.fandango.com/ImageRenderer/0/0/redesign/static/img/default_poster.png/0/images/MasterRepository/fandango/209946/SgtStubby2018.jpg" style="height:300px"/>
      </div>
      <div class="col-md-9">
        <h4><strong>Synposis</strong></h4>
        <p>"With World War I looming, a young Army Pvt. Robert Conroy is adopted by a stray, stump-tailed terrier. Conroy names his new friend Stubby and gives him a home, a family, and a chance to embark on the adventure that would define a century. The two quickly find themselves in the trenches of France and on the path to history. French soldier Gaston Baptiste befriends the duo and accompanies them along their epic journey through harsh conditions and incredible acts of courage."
        – Google Reviews</p>
        <h4><strong>From the Makers</strong></h4>
        <p>SGT. STUBBY: AN AMERICAN HERO is an upcoming computer-animated feature film based on the incredible true story of America’s most decorated dog. After being rescued off the streets by a young Soldier on the eve of America’s entry in World War I, Stubby is given a home, a family, and the chance to embark on the adventure that would define a century.</p>
        <p>Visit the Sgt. Stubby <a href="http://www.stubbymovie.com/">website</a>.</p>
      </div>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="row">
  <h2>All Movies</h2>
  {% for m in movies %}
    {% if forloop.first %}<div class="row">{% endif %}
    <div class="col-md-4">
      <div class="boxes-cols">
        <h4><a href='{% url "theaters:movies-detail" m.movid %}'>{{m.title}}</a></h4>
        <img src='http:{{ m.poster }}' style='height:300px; width=100%'/>
        <br><br>
        <div>
        <span class="btn btn-primary btn-xs rounded-pill">{{m.genres}}</span>
        <span class="btn btn-primary btn-xs rounded-pill">{{m.rating}}</span>
        </div>
      </div>
    </div>
    {% if forloop.counter|divisibleby:3 %}</div><br><div class="row">{% endif %}
    {% if forloop.last %}</div>{% endif %}
  {% endfor %}
  </div>
</div>

{% endblock %}

fand/fand/theaters/templates/fand/list_showtimes.html
{% extends "fand/base.html" %}

{% block content %}
All Showtimes Here
{% endblock %}

fand/fand/theaters/templates/fand/list_theaters.html
{% extends "fand/base.html" %}
{% load static %}
<link href="{% static "fand/css/boot.css" %}" rel="stylesheet">

{% block content %}
<br>
<div class="row">
  <div class="col-md-12">
  <h1>Theaters</h1>
  <h2>Overview</h2>
  <h3>Map</h3>
  <p>Wondering where you could catch a show? We've got you covered.</p>
  <div id="map"></div><br>
  <h3>Runtimes</h3>
  <p>Got a short attention span (or kids with short attention spans)? Look at what movies have the shortest runtimes. Or if you think it'll get you the most bang for your buck, look for the longest showtime.</p>
  <div id="movie-bar"></div><br>
  <h2>Locations by City</h2>
  <p>Click on a theater to see what's showing there.</p>

    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h3>Durham</h3>
          <ul>
          {% for t in theaters %}
            {% if t.city == "Durham" %}
              <li><h5><a href='{% url "theaters:theaters-detail" t.id %}'>{{t.theaterName}}</a></h5>
              <p>{{t.addressOne}}<br> {{t.city}}, NC {{t.zip}}<br>
              <a href='https://www.google.com/maps/search/{{t.addressOne}} {{t.city}}'>Route</a></p>
              </li>
            {% endif %}
          {% endfor %}
          </ul>
        </div>
        <div class="col-md-6">
          <h3>Chapel Hill</h3>
          <ul>
          {% for t in theaters %}
            {% if t.city == "Chapel Hill" %}
              <li><h5><a href='{% url "theaters:theaters-detail" t.id %}'>{{t.theaterName}}</a></h5>
              <p>{{t.addressOne}}<br> {{t.city}}, NC {{t.zip}}<br>
              <a href='https://www.google.com/maps/search/{{t.addressOne}} {{t.city}}'>Route</a></p>
            </li>
            {% endif %}
          {% endfor %}
          </ul>
        </div>
      </div><br>
      <div class="row">
        <div class="col-md-6">
          <h3>Raleigh</h3>
          <ul>
          {% for t in theaters %}
            {% if t.city == "Raleigh" %}
              <li><h5><a href='{% url "theaters:theaters-detail" t.id %}'>{{t.theaterName}}</a></h5>
              <p>{{t.addressOne}}<br> {{t.city}}, NC {{t.zip}}<br>
              <a href='https://www.google.com/maps/search/{{t.addressOne}} {{t.city}}'>Route</a></p>
              </li>
            {% endif %}
          {% endfor %}
          </ul>
        </div>
        <div class="col-md-6">
          <h3>Other Triangle Locations</h3>
          <ul>
          {% for t in theaters %}
            {% if t.city != "Raleigh" and t.city != "Chapel Hill" and t.city != "Durham" %}
              <li><h5><a href='{% url "theaters:theaters-detail" t.id %}'>{{t.theaterName}}</a></h5>
              <p>{{t.addressOne}}<br> {{t.city}}, NC {{t.zip}}<br>
              <a href='https://www.google.com/maps/search/{{t.addressOne}} {{t.city}}'>Route</a></p>
            </li>
            {% endif %}
          {% endfor %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDhBnuGExtxxL0XSsIs7PTH8w624cX25ek&callback=initMap">
</script>

{% endblock %}

fand/fand/theaters/templates/fand/movie.html
{% extends "fand/base.html" %}

{% block content %}
<br>
<div class="container">
  <div class="row">
    <div class="col-md-6">
    <h1>{{ m.title }}</h1>
    <img src='http:{{ m.poster }}' style='height:600px; width=100%'>
    </div>
    <div class="col-md-6">
      <br><br>
    <h2>Movie Information</h2>
    <h5><strong>Details</strong></h5>
    <p><strong>Rating:</strong></h5> {{ m.rating }}</p>
    <p><strong>Runtime:</strong></h5> {{ m.runtime }} minutes</p>
    <p><strong>Genres:</strong></h5> {{ m.genres }}</p>
    <h5><strong>Locations and showtimes:</strong></h5>
    <ul>
    {% for key, value in consolidated.items %}
      <li>
        <strong><a href='{% url "theaters:theaters-detail" key.id %}'>{{key}}</a></strong>
        <p>
        {% for st in value %}
          <a href='{{st.ticketingUrl}}'>{{st.time}}</a>
        {% endfor %}
        </p>
      </li>
    {% endfor %}
    </ul>
    </div>
  </div>
</div>





{% endblock %}

fand/fand/theaters/templates/fand/theater.html
{% extends "fand/base.html" %}

{% block content %}

<br>
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>{{t.theaterName}}</h1>
      <h3>About this location</h3>
      <p><strong>Address: </strong><br><a href='https://www.google.com/maps/search/{{t.addressOne}} {{t.city}}'>{{t.addressOne}}<br> {{t.city}}, NC {{t.zip}}</a></p>
      <p><strong>Age Policy:</strong> {{t.agePolicy}}</p>
      <p><strong>Phone:</strong> {{t.phone}}</p>
      <h3>Movies Playing</h3>

      <ul>
      {% for key, value in consolidated.items %}
        <li>
          <h5><strong><a href='{% url "theaters:movies-detail" key.movid %}'>{{key}}</a></strong></h5>
          Showtimes:
        {% for st in value %}
        <a href='{{st.ticketingUrl}}'>{{st.time}}</a>
        {% endfor %}
      </li><br>
      {% endfor %}
      </ul>


    </div>
  </div>
</div>
{% endblock %}